### PR TITLE
Fixed issue with overlapping scaled circle markers

### LINKED ISSUE #17: Overlapping scaled circle markers
image

### PR DESCRIPTION
**Pull request by JacobBrandt**
Fixes #17 

Original
screen shot 2016-12-12 at 1 22 46 pm

New
screen shot 2016-12-12 at 1 21 45 pm

### CODE REVIEW

**Comment by JacobBrandt** [comment]
I'm thinking of taking out the scaleFactor.  I just used the same one from ShadedCircleMarkers for consistency.  However I think I like the visual look of it without the size losing 20%, especially since these are scaled circles and get rather small.  Play around with it set to 1 and let me know what you think.

Here's an example without the scaleFactor.
screen shot 2016-12-12 at 1 40 52 pm

**Comment by nreese** [comment]
What are the allmin and allmax parameters? I do not really understand what `_scaleValueBetween` is doing. Can you explain? Looks like you can get a divide by zero if allmin and allmax are the same. This happened for me when the scale factor was set to one and the map zoom level was set to 4.

image

**Comment by JacobBrandt** [comment]
Ah yes, the infamous divide by zero.  I'll fix that.

The allmin and allmax parameters are the min and max values of all the features on the map.

The scaleValueBetween is basically a rescaling function.  It applies a scaling factor to a translated value and then retranslates that value to the new minimum.  So (max-min)/(orgMax-orgMin) is the scaling factor.  (value-orgMin) is the translation that we apply to the scaling factor and +min is used to translate the value to the new minimum.  This works for values that are known to already be within the range orgMin to orgMax.  In our case we know this to be true and we have the range from the all* parameters.

So now for all values within the range orgMin to orgMax this will return values within a new range of min to max.

**Comment by nreese** [comment]
That seems overly complicated since the feature value is on the same scale as allmax and allmin. Really we just want to make sure the radius is never too small right? How about something a little more explicit like this

```
ScaledCircleMarker.prototype._geohashMinDistance = function (feature) {
      const centerPoint = _.get(feature, 'properties.center');
      const geohashRect = _.get(feature, 'properties.rectangle');

      // centerPoint is an array of [lat, lng]
      // geohashRect is the 4 corners of the geoHash rectangle
      //   an array that starts at the southwest corner and proceeds
      //   clockwise, each value being an array of [lat, lng]

      // center lat and southeast lng
      const east   = L.latLng([centerPoint[0], geohashRect[2][1]]);
      // southwest lat and center lng
      const north  = L.latLng([geohashRect[3][0], centerPoint[1]]);

      // get latLng of geohash center point
      const center = L.latLng([centerPoint[0], centerPoint[1]]);

      // get smallest radius at center of geohash grid rectangle
      const eastRadius  = Math.floor(center.distanceTo(east));
      const northRadius = Math.floor(center.distanceTo(north));
      const radius = _.min([eastRadius, northRadius]);
      const minRadius = radius / 3;

      // allmax/allmin is max/min of all values
      const scale = this.geoJson.properties.allmax - this.geoJson.properties.allmin;
      
      let scaledRadius = radius;
      if (scale !== 0) {
        scaledRadius = (feature.properties.value / scale) * radius;
        if (scaledRadius < minRadius) scaledRadius = minRadius;
      }
      return scaledRadius;
    };
```

**Comment by JacobBrandt** [comment]
So I'm changing the L.circle to L.circleMarker because L.circle is rounding the radius and the original scaled circles did not do this.  That's my mistake I should have looked at the difference between these.  Changing to circleMarker should give more accurate sized circles because it will allow fractional variance which is imperative in this kind of visualization and does a better job visualizing the differences on our approaches.

So about your solution.  Yes it's simplistic but it has shortcomings.  It basically says ignore values below 33% of the scale, because only at 33% is the size relative to the rest of the scale model.  That is not equivalent to what my solution is doing.  My solution keeps all sizes relative to the scale model.  We can go with your approach its just that you'll have to explain that sizes below 33% of max are not relative to the model.

For reference look at these two images.  They both are now using circleMarker which means no rounding of the circle radius is occurring.  This will help highlight the differences.  This first one is your approach.  There's only 2 distinct sizes; those below 33% and the one at max size.
screen shot 2016-12-13 at 12 17 00 pm

And here is an image of my solution.  Notice the difference in sizes across all values.  This image shows all sizes are relative to one another across the entire range of values.
screen shot 2016-12-13 at 12 17 11 pm

**Comment by nreese** [comment]
Thanks for the explanation and visuals. Lets stick to your method. I did not understand the difference between the two until now.

**Comment by nreese** [comment]
Looks great. Thanks for walking me through everything.

**Pull request merged**
